//! Base ICC type definitions
use crate::Signature;

pub const CHROMATICITY: Signature = Signature::new(b"chrm");
pub const COLORANT_ORDER: Signature = Signature::new(b"clro");
pub const COLORANT_TABLE: Signature = Signature::new(b"clrt");
pub const CRD_INFO: Signature = Signature::new(b"crdi");
pub const CURVE: Signature = Signature::new(b"curv");
pub const DATA: Signature = Signature::new(b"data");
pub const DICT: Signature = Signature::new(b"dict");
pub const DATE_TIME: Signature = Signature::new(b"dtim");
pub const DEVICE_SETTINGS: Signature = Signature::new(b"devs");
pub const LUT16: Signature = Signature::new(b"mft2");
pub const LUT8: Signature = Signature::new(b"mft1");
pub const LUTA_TO_B: Signature = Signature::new(b"mAB ");
pub const LUTB_TO_A: Signature = Signature::new(b"mBA ");
pub const MEASUREMENT: Signature = Signature::new(b"meas");
pub const MULTI_LOCALIZED_UNICODE: Signature = Signature::new(b"mluc");
pub const MULTI_PROCESS_ELEMENT: Signature = Signature::new(b"mpet");
#[deprecated]
pub const NAMED_COLOR: Signature = Signature::new(b"ncol");
pub const NAMED_COLOR2: Signature = Signature::new(b"ncl2");
pub const PARAMETRIC_CURVE: Signature = Signature::new(b"para");
pub const PROFILE_SEQUENCE_DESC: Signature = Signature::new(b"pseq");
pub const PROFILE_SEQUENCE_ID: Signature = Signature::new(b"psid");
pub const RESPONSE_CURVE_SET16: Signature = Signature::new(b"rcs2");
pub const S15_FIXED16_ARRAY: Signature = Signature::new(b"sf32");
pub const SCREENING: Signature = Signature::new(b"scrn");
pub const SIGNATURE: Signature = Signature::new(b"sig ");
pub const TEXT: Signature = Signature::new(b"text");
pub const TEXT_DESCRIPTION: Signature = Signature::new(b"desc");
pub const U16_FIXED16_ARRAY: Signature = Signature::new(b"uf32");
pub const UCR_BG: Signature = Signature::new(b"bfd ");
pub const UINT16_ARRAY: Signature = Signature::new(b"ui16");
pub const UINT32_ARRAY: Signature = Signature::new(b"ui32");
pub const UINT64_ARRAY: Signature = Signature::new(b"ui64");
pub const UINT8_ARRAY: Signature = Signature::new(b"ui08");
pub const VCGT: Signature = Signature::new(b"vcgt");
pub const VIEWING_CONDITIONS: Signature = Signature::new(b"view");
pub const XYZ: Signature = Signature::new(b"XYZ ");
