[package]
authors = ["Stefan Kewatt <stefan.kewatt@gmail.com>"]
edition = "2018"
name = "lcms2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
